app/models/meal_plan.py
from .. import db
from datetime import datetime
"""
This module defines meal plan class. A meal plan is created and
the details can be updated or deleted

"""

class Meal_plan(db.Model):
    """ This class defines Meal_plan by various attributes"""
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    title = db.Column(db.String(120), nullable=False)
    description = db.Column(db.String(120), nullable=True)
    start_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    end_date = db.Column(db.DateTime,nullable=False, default=datetime.utcnow)
    created_at = db.Column(db.DateTime,nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime,nullable=False, default=datetime.utcnow)
    groceries = db.relationship('Grocery', backref='meal_plan', lazy=True,cascade='all, delete-orphan')
    recipes = db.relationship('AllRecipe', secondary='mealplan_recipe', backref='meal_plan')

    def __repr__(self):
        return f"'{self.title}, Created On {self.created_at}"
    
    def save(self):
        """saves the meal plan to the database"""
        db.session.add(self)
        db.session.commit()

    def update(self, title=None, description=None, start_date=None, end_date=None):
        """updates the meal plan and saves the new plan in the database"""
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        if start_date is not None:
            self.start_date = start_date
        if end_date is not None:
            self.end_date = end_date
        db.session.commit()
    
    def delete(self):
        """delete the meal plan from the database"""
        db.session.delete(self)
        db.session.commit()

app/models/recipe.py
from .. import db
from datetime import datetime
"""
This module defines the class Recipe 

"""

class SavedRecipe(db.Model):
    """This class defines Recipe with various attributes"""
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    name = db.Column(db.String(100), nullable=False)
    ingredients = db.Column(db.JSON, nullable=False)
    instructions = db.Column(db.JSON, nullable=False)
    diet_type = db.Column(db.String(150))
    allergies = db.Column(db.JSON)
    image_file = db.Column(db.String(120), nullable=False)
    nutrients = db.Column(db.Text, nullable=True)

    def __repr__(self):
        return f'<Recipe {self.name}>'
    
    def save(self):
        """save the recipe to the database"""
        existing_recipe = SavedRecipe.query.filter_by(user_id=self.user_id, name=self.name).first()

        if existing_recipe:
            print(f"Recipe '{self.name}' already exists in user's saved recipes '{self.user_id}'")
            return False
        else:
            try:
                db.session.add(self)
                db.session.commit()
                return True
            except Exception as e:
                print(f"Error saving recipe: {e}")
                db.session.rollback()
                return False
    
    def update(self, name=None, ingredients=None, instructions=None, diet_type=None, allergies=None):
        """update the recipe's details"""
        if name is not None:
            self.name = name
        if ingredients is not None:
            self.ingredients = ingredients
        if instructions is not None:
            self.instructions = instructions
        if allergies is not None:
            self.allergies = allergies
        if diet_type is not None:
            self.diet_type = diet_type
        db.session.commit()
    def delete(self):
        """Delete the Recipe from the database"""
        db.session.delete(self)
        db.session.commit()

app/api/routes.py
from flask import Blueprint, render_template, request, current_app, jsonify
from flask import flash, redirect, url_for
import requests
from flask_login import login_required, current_user, login_user, logout_user
from app.models.user import User
from app.models.all_recipes import AllRecipe
from app.models.meal_plan import Meal_plan
from app.models.recipe import SavedRecipe
from app.helpers.helpers import get_recipes
from app.models.scheduled_recipes import ScheduledRecipes
from app.models.mealPlanRecipe import MealplanRecipe
from app.models.forms import AddToMealPlanForm, UpdateuserForm
from app import db
import json


api = Blueprint('api', __name__)


"""Landing page route"""
@api.route('/')
def home():
    return render_template('home.html')


""" User dahsboard """
@api.route('/dashboard/<int:user_id>/<string:username>', methods=['GET', 'POST'])
@login_required
def dashboard(user_id, username):

    """
    Render the dashboard template with the fetched data

    """
    user_id = current_user.id
    username = current_user.username
    # Validate that the logged-in user matches the user in the URL
    if current_user.id != user_id or current_user.username != username:
        flash("Unauthorized access.", "danger")
        return redirect(url_for('auth.login'))
    # saved_recipe = saved_recipes(user_id)
    saved_recipes = SavedRecipe.query.filter_by(user_id=current_user.id).all()
    total_saved_recipes = len(saved_recipes)

    # get the most recent recipe added by the user
    recent_recipe = SavedRecipe.query.filter_by(user_id=current_user.id).order_by(SavedRecipe.id.desc()).first()

    # Fetch the recommended Recipes
    recommended_recipes = get_recipes(db=db ,user=current_user)

    return render_template(
        'dashboard.html',
        recommended_recipes=recommended_recipes,
        total_saved_recipes=total_saved_recipes,
        user=current_user,
        user_id=user_id,
        username=username,
        recent_recipe=recent_recipe,
    )


"""search recipe route"""
@api.route('/search_recipe', methods=['GET', 'POST'])
@login_required
def search_recipe():
    keyword = request.args.get('query', '').strip()
    recipes = get_recipes(db=db, keyword=keyword, user=current_user)
    recent_recipe = SavedRecipe.query.filter_by(user_id=current_user.id).order_by(SavedRecipe.id.desc()).first()
    return render_template(
        'dashboard.html',
        recipes=recipes,
        user=current_user,
        user_id=current_user.id,
        recent_recipe=recent_recipe
    )


"""Displays the recipe details"""
@api.route('/recipe_detail/<int:recipe_id>', methods=['GET'])
@login_required
def recipe_detail(recipe_id):
    recipe = AllRecipe.query.get_or_404(recipe_id)
    return render_template(
        'recipe_detail.html',
        recipe_id = recipe.id,
        recipe=recipe,
        user=current_user,
        user_id=current_user.id
    )


"""Displays user's Meal Plan"""
@api.route('/meal_plan', methods=['GET'])
@login_required
def meal_plan():
    user = current_user
    meal_plan = Meal_plan.query.filter_by(user_id=user.id).first()
    if not meal_plan:
        flash("You have not created any meal plans yet", "info")
        unscheduled_recipes = []  # No recipes to show if no meal plan exists
        scheduled_recipes = []
        calendar_events = []
        meal_plan_id = None
        return render_template(
            'meal_plan.html',
            user=current_user.username,
            user_id=current_user.id,
            scheduled_recipes=scheduled_recipes,
            unscheduled_recipes=unscheduled_recipes,
            calendar_events=calendar_events,
            meal_plan_id=meal_plan_id
            )
    else:
        unscheduled_recipes = [
            recipe for recipe in meal_plan.recipes 
            if not any(sr.recipe_id == recipe.id for sr in meal_plan.scheduled_recipes)
        ]
        # Fetch scheduled recipes
        scheduled_recipes = ScheduledRecipes.query.join(Meal_plan).filter(Meal_plan.user_id == current_user.id).all()
        # Convert scheduled recipes to JSON for FullCalendar
        calendar_events = [{
            'title': scheduled_recipe.recipe.name,
            'start': scheduled_recipe.start_time.isoformat(),
            'end': scheduled_recipe.end_time.isoformat(),
            'url': url_for('api.recipe_detail', recipe_id=scheduled_recipe.recipe_id)
        } for scheduled_recipe in scheduled_recipes]

    return render_template(
        'meal_plan.html',
        meal_plan=meal_plan,
        scheduled_recipes = scheduled_recipes,
        user=current_user,
        recipes=unscheduled_recipes,
        user_id=current_user.id,
        calendar_events=calendar_events,
        meal_plan_id=meal_plan.id
    )


"""Schedule a recipe """
@api.route('/schedule_recipe', methods=['POST'])
@login_required
def schedule_recipe():
    data = request.get_json()
    recipe_id = data.get('recipe_id')
    meal_plan_id = data.get('meal_plan_id')
    start_time = data.get('start_time')
    end_time = data.get('end_time')
    if not recipe_id or not start_time or not end_time or not meal_plan_id:
        return {"success":False, "message": "Missing required data."}, 400
    
    meal_plan = MealplanRecipe.query.filter_by(meal_plan_id=meal_plan_id, recipe_id=recipe_id).first()
    if not meal_plan:
        return jsonify({'error': 'Meal Plan ID is required'}), 400
    # Ensure the recipe exists
    recipe = AllRecipe.query.get_or_404(recipe_id)

    # Create a scheduled recipe instance
    scheduled_recipe = ScheduledRecipes(
        meal_plan_id = meal_plan_id,
        recipe_id=recipe.id,
        start_time=start_time,
        end_time=end_time
    )

    db.session.add(scheduled_recipe)
    db.session.commit()

    # Return success response
    return {
        'success': True,
        # 'meal_plan_id': meal_plan.id,
        'recipe_name': recipe.name,
        'start_time': start_time,
        'end_time': end_time
    }


"""Saves the recipe"""
@api.route('/save_recipe/<int:recipe_id>', methods=['POST'])
@login_required
def save_recipe(recipe_id):
    """Save the recipe to the user's meal plan."""
    user_id = current_user.id
    recipe = AllRecipe.query.get_or_404(recipe_id)

    """ Created a saved Recipe instacnce"""
    saved_recipe = SavedRecipe(
        id=recipe_id,
        user_id = user_id,
        name=recipe.name,
        ingredients=recipe.ingredients,
        instructions=recipe.instructions,
        diet_type=recipe.diet_type,
        allergies=recipe.allergies,
        image_file=recipe.image_url,
        nutrients=recipe.nutrients
    )
    if saved_recipe.save():
        message = 'Recipe Saved'
        flash(message, 'success')
        return redirect(url_for(
            'api.recipe_detail',
            recipe_id=recipe.id,
            user_id=user_id
        ))
    else:
        flash("Recipe already exists in your collection")
        return redirect(url_for(
            'api.recipe_detail',
            recipe_id=recipe.id,
            user_id=user_id
        ))


@api.route('/delete_saved_recipe/<int:recipe_id>', methods=['POST'])
@login_required
def delete_saved_recipe(recipe_id):
    saved_recipe = SavedRecipe.query.filter_by(user_id=current_user.id, id=recipe_id).first()

    if not saved_recipe:
        return jsonify({'error': 'Recipe not found in your saved recipes'}), 404
    
    saved_recipe.delete()

    return jsonify({'success': 'Recipe deleted successfully'}), 200



"""display the saved recipes"""
@api.route('/saved_recipes/<int:user_id>')
@login_required
def saved_recipes(user_id):

    if user_id != current_user.id:
        abort(403)
    # query the user's saved recipes
    saved_recipes = SavedRecipe.query.filter_by(user_id=current_user.id).all()

    if not saved_recipes:
        flash("No saved Recipes Found", "info")
    return render_template(
        'saved_recipes.html',
        saved_recipes=saved_recipes,
        user_id=current_user.id, user=current_user
    )



""" Adds the recipe to meal plan"""
@api.route('/add_to_mealplan/<int:recipe_id>', methods=['POST'])
@login_required
def add_to_mealplan(recipe_id):
    errors = {}
    recipe = AllRecipe.query.get_or_404(recipe_id)
    meal_plan = Meal_plan.query.filter_by(user_id=current_user.id).first()

    if not meal_plan:
        # Create a new meal plan if none exists
        meal_plan = Meal_plan(user_id=current_user.id, title="My Meal Plan")
        db.session.add(meal_plan)
        db.session.commit()
        return redirect(url_for('api.recipe_detail', recipe_id=recipe.id))
    if recipe in meal_plan.recipes:
        errors['meal_plan'] = 'Meal Plan already added'
        flash("Recipe already in the meal Plan!", 'warning')
    else:
        meal_plan.recipes.append(recipe)
        db.session.commit()
    return redirect(url_for('api.recipe_detail', recipe_id=recipe.id,meal_plan_id=meal_plan.id))


@api.route('/delete_scheduled_recipe/<int:meal_plan_id>/<int:recipe_id>', methods=['POST'])
@login_required
def delete_scheduled_recipe(meal_plan_id, recipe_id):
    print(f"Received meal_plan_id: {meal_plan_id}, recipe_id: {recipe_id}")
    # Fetch the scheduled recipe from the database
    scheduled_recipe = ScheduledRecipes.query.filter_by(meal_plan_id=meal_plan_id, recipe_id=recipe_id).first()
    if not scheduled_recipe:
        return jsonify({'success': False, 'error': 'Recipe not found in the meal plan'}), 404

    if scheduled_recipe:
        db.session.delete(scheduled_recipe)

        # Remove the recipe from the meal plan as well
        meal_plan = Meal_plan.query.get(meal_plan_id)
        recipe_to_remove = AllRecipe.query.get(recipe_id)
        
        if recipe_to_remove in meal_plan.recipes:
            meal_plan.recipes.remove(recipe_to_remove)

        db.session.commit()
        return jsonify(success=True)
    else:
        return jsonify(success=False, error="Scheduled recipe not found"), 404


"""Display the user's profile and  update"""

app/templates/dashboard.html
{% extends "layout2.html" %}

{% block title %} Dashboard {% endblock %}

{% block extra_styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/dashboard.css') }}">
{% endblock %}

{% block content %}
<main class="dashboard">
    <!-- <div class="dashboard-pic">
         <img src="{{url_for('static', filename='img/download.png')}}" alt=""> -->
         <!-- <h3>looking For Recipe? Don't worry we will sort you out</h3> -->
    <!-- </div> --> 
    <h3>Welcome {{user.username}}</h3>
    <section class="stats-section">
        <div class="card user-stats">
            <h3>Statistics</h3>
            <p>Total Saved Recipes: {{total_saved_recipes}}</p>
        </div>
        <div class="card recent-activities">
            <h3>Recent Activities</h3>
            {% if recent_recipe %}
            <p>Added a new recipe: "{{recent_recipe.name}}"</p>
            {%else%}
                <p> No recipe added recently</p>
            {% endif%}
        </div>
         <!-- <div class="card tasks">
            <h3>Tasks</h3>
            <ul>
                <li><input type="checkbox"> Try the new "Vegan Burger" recipe</li>
                <li><input type="checkbox"> Plan meals for the weekend</li>
                <li><input type="checkbox"> Update pantry inventory</li>
            </ul>
        </div> -->
    </section>
    
    <div class="search">
        <form action="{{ url_for('api.search_recipe') }}" class="search-form" method="GET">
            <input type="text" name="query" placeholder="Search 1500+ recipes" required>
            <!-- <button type="submit">Search</button> -->
        </form>
    </div>
    {% if recommended_recipes %}
        <h3>Recommended Recipes</h3>
    {% endif %}
    <section class="recipes">
        {% if recommended_recipes %}
            {% for recipe in recommended_recipes %}
            <div class="recipe-card">
                <div class="details">
                    <img src="{{ recipe.image_url }}" alt="{{ recipe.name }}">
                    <h4>{{ recipe.name }}</h4>
                    <p>Diet Type: {{ recipe.diet_type }}</p>
                    <a href="{{url_for('api.recipe_detail', recipe_id=recipe.id)}}">View Recipe</a>
                </div>
            </div>
            {% endfor %}
        {% endif %}
    </section>
    <section class="recipes">
        {% if recipes %}
            {% for recipe in recipes %}
            <div class="recipe-card">
                <div class="details">
                    <img src="{{ recipe.image_url }}" alt="{{ recipe.name }}">
                    <h4>{{ recipe.name }}</h4>
                    <p>Diet Type: {{ recipe.diet_type }}</p>
                    <a href="{{url_for('api.recipe_detail', recipe_id=recipe.id)}}">View Recipe</a>
                </div>
                <!-- <img src="{{ recipe.image_url }}" alt="{{ recipe.name }}">
                <h4>{{ recipe.name }}</h4>
                <p>Diet Type: {{ recipe.diet_type }}</p>
                <a href="{{url_for('api.recipe_detail', recipe_id=recipe.id)}}">View Recipe</a> -->
            </div>
            {% endfor %}
        {% else %}
            <p>No recipes found.</p>  <!-- Fallback message -->
        {% endif %}
    </section>
</main>
{% endblock %}

app/templates/home.html
{% extends "layout.html" %}

{% block extra_styles %}<link rel="stylesheet" href="{{ url_for('static', filename='styles/home.css') }}">{% endblock %}
{% block content %}
<main>
    <div class="image">
        <img src="{{url_for('static', filename='img/content2.png')}}" alt="">
        <img src="{{url_for('static', filename='img/content3.png')}}" alt="">
    </div>
    <section class="main-container">
        <section class="sub-container-1">
            <div class="text">
                <img src="{{url_for('static', filename='img/log3.png')}}" alt="hello">
                <h1>Smart Recipe Planner</h1>
                <p>A home of delicious Recipes. Find out Thousands of Recipes on your fingertip!</p>
                <form action="{{url_for('auth.register')}}" methos="POST">
                    <button class="button-action" type="submit"> Get Started!</button>
                </form>
            </div>
        </section>
        <section class="sub-container-2">
            <img src="{{url_for('static', filename='img/landing1.jpg')}}" alt="hello">
        </section>
    </section>
    <section class="container-2">
        <section class="cont-1">
            <img src="{{url_for('static', filename='img/landing4.png')}}" alt="">
        </section>
        <section class="cont-2">
            <div class="text-2">
                <p>Choose any kind of Recipe according to your preference and diet type. Eat healthier at your comfort with Thousands of recipes you can choose from</p>
            </div>
        </section>
    </section>
    <section class="features-container">
        <h2>Key Features</h2>
        <div class="features-grid">
            <div class="feature-card">
                <svg xmlns="http://www.w3.org/2000/svg" width="30"  height="30" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                    <path fill-rule="evenodd" d="M7.5 6a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0ZM3.751 20.105a8.25 8.25 0 0 1 16.498 0 .75.75 0 0 1-.437.695A18.683 18.683 0 0 1 12 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 0 1-.437-.695Z" clip-rule="evenodd" />
                  </svg>
                    
                <h3>Personalized Recipes</h3>
                <p>Recipes are tailored to your diet type and preferences.</p>
            </div>
            <div class="feature-card">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                    <path d="M11.625 16.5a1.875 1.875 0 1 0 0-3.75 1.875 1.875 0 0 0 0 3.75Z" />
                    <path fill-rule="evenodd" d="M5.625 1.5H9a3.75 3.75 0 0 1 3.75 3.75v1.875c0 1.036.84 1.875 1.875 1.875H16.5a3.75 3.75 0 0 1 3.75 3.75v7.875c0 1.035-.84 1.875-1.875 1.875H5.625a1.875 1.875 0 0 1-1.875-1.875V3.375c0-1.036.84-1.875 1.875-1.875Zm6 16.5c.66 0 1.277-.19 1.797-.518l1.048 1.048a.75.75 0 0 0 1.06-1.06l-1.047-1.048A3.375 3.375 0 1 0 11.625 18Z" clip-rule="evenodd" />
                    <path d="M14.25 5.25a5.23 5.23 0 0 0-1.279-3.434 9.768 9.768 0 0 1 6.963 6.963A5.23 5.23 0 0 0 16.5 7.5h-1.875a.375.375 0 0 1-.375-.375V5.25Z" />
                  </svg>
                  
                <h3>Recipe Search</h3>
                <p>Search for recipes using ingredients or meal types and view detailed instructions.</p>
            </div>
            <div class="feature-card">
                <h3>Meal Planning</h3>
                <p>Add recipes to your meal plan and organize your weekly meals.</p>
            </div>
            <div class="feature-card">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30"   fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="black" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 3.75V16.5L12 14.25 7.5 16.5V3.75m9 0H18A2.25 2.25 0 0 1 20.25 6v12A2.25 2.25 0 0 1 18 20.25H6A2.25 2.25 0 0 1 3.75 18V6A2.25 2.25 0 0 1 6 3.75h1.5m9 0h-9" />
                  </svg>
                  
                <h3>Save Recipes</h3>
                <p>Save your favorite recipes and view them later with one click.</p>
            </div>
            <div class="feature-card">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" width="30" height="30"  viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 2.994v2.25m10.5-2.25v2.25m-14.252 13.5V7.491a2.25 2.25 0 0 1 2.25-2.25h13.5a2.25 2.25 0 0 1 2.25 2.25v11.251m-18 0a2.25 2.25 0 0 0 2.25 2.25h13.5a2.25 2.25 0 0 0 2.25-2.25m-18 0v-7.5a2.25 2.25 0 0 1 2.25-2.25h13.5a2.25 2.25 0 0 1 2.25 2.25v7.5m-6.75-6h2.25m-9 2.25h4.5m.002-2.25h.005v.006H12v-.006Zm-.001 4.5h.006v.006h-.006v-.005Zm-2.25.001h.005v.006H9.75v-.006Zm-2.25 0h.005v.005h-.006v-.005Zm6.75-2.247h.005v.005h-.005v-.005Zm0 2.247h.006v.006h-.006v-.006Zm2.25-2.248h.006V15H16.5v-.005Z" />
                  </svg>
                  
                <h3>Schedule Recipes</h3>
                <p>Schedule recipes easily and integrate them into your calendar.</p>
            </div>
        </div>
    </section>
    <section class="About-container">
        <h2> About Us</h2>
        <p>The Smart Recipe Planner is designed to offer users a personalized and convenient way to manage their meals and dietary preferences. Whether you're looking to follow a specific diet, discover new recipes, or organize your weekly meals, the Smart Recipe Planner makes the process simple and enjoyable.</p>
        <p>This platform provides thousands of recipes tailored to various preferences, complete with the ability to plan meals, and schedule recipes using an integrated calendar. Our goal is to help users eat healthier and manage their diets more effectively.</p>
        <section>
            <ul>
                <h2>Social Media</h2>
                <ion-icon name="logo-github"></ion-icon> <a href="https://github.com/abdirashidabubakar50/Recipe_Planner">github</a>
            </ul>
        </section>
    </section>
</main>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{url_for('static', filename='img/log3.png')}}" type="image/x-icon">
    <title>{% block title %}Smart Recipe Planner{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css') }}">
</head>
<body>
    <header>
        <div class="header-content">
            <div class="logo">
                <a href=""><img src="{{url_for('static', filename='img/log3.png')}}" alt="">RecipePlanner</a>
                {% block extra_styles %}{% endblock %}
            </div>
            <nav>
                <ul>
                    <li><a href="{{url_for('api.home')}}">Home</a></li>
                    <li><a href="{{url_for('auth.register')}}">Register</a></li>
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer class="footer-main">
        <p>&copy; 2024 Smart Recipe Planner. All rights reserved.</p>
    </footer>
</body>
</html>

app/templates/layout2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" href="{{url_for('static', filename='img/log3.png')}}" type="image/x-icon">
    <title>{% block title %}Smart Recipe Planner{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/dashboard.css') }}">
</head>
<body>
    <header class="navbar">
        <div class="logo">
            <!-- <img src="{{url_for('static', filename='img/log3.png')}}" alt=""> -->
            <a href="" class="logo-text"><img src="{{url_for('static', filename='img/log3.png')}}" alt="">Recipe Planner</a>
            {% block extra_styles %}{% endblock %}
        </div>
        <nav class="nav-links">
            <a href="{{url_for('api.dashboard', user_id=current_user.id, username=current_user.username)}}">Dashboard</a>
            <div class="dropdown">
                <a href="{{ url_for('api.search_recipe') }}" class="dropdown-link">Recipes</a>
                <div class="dropdown-content">
                    <a href="{{ url_for('api.search_recipe') }}">Search Recipes</a>
                    <a href="{{url_for('api.saved_recipes', user_id=current_user.id)}}">Saved Recipes</a>
                </div>
            </div>
            <a href="{{url_for('api.meal_plan')}}">Meal Plans</a>
            <a href="{{url_for('api.profile', user_id=user_id)}}">Settings</a>
        </nav>
        <div class="user-info">
            <span>{{user.username}}</span>
            <a href="{{url_for('api.profile', user_id=user_id)}}"><img src="{{url_for('static', filename='img/profile.png')}}" alt="Profile Picture" class="profile-pic"></a>
        </div>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer class="footer-main" style="display: none">
        <p>&copy; 2024 Smart Recipe Planner. All rights reserved.</p>
    </footer>
</body>
</html>

app/templates/login.html
{% extends "layout.html" %}

{% block title %} Login {% endblock %}

{% block extra_styles %}<link rel="stylesheet" href="{{ url_for('static', filename='styles/login.css') }}">{% endblock %}
{% block content %}
<div class="login-container">
    <div class="form-content">
        <button class="google-btn">
            <img src="{{url_for('static', filename='img/google.png')}}"  alt="Google logo" class="google-logo">
            <a href="{{ url_for('auth.google_login') }}" class="google-text">Continue with Google</a>
        </button>
        <form action="{{url_for('auth.login')}}" method="POST">
            {{ form.csrf_token }}
            <div class="form-group">
                <label for="Email">Email</label>
                <input type="email" id="email" name="email" placeholder="email" required>
                {% if errors.get('email') %}
                    <small class="error">{{ errors['email'] }}</small>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" placeholder="password" required>
                {% if errors.get('password') %}
                    <small class="error">{{ errors['password'] }}</small>
                {% endif %}
            </div>
           <button type="submit" class="login-button">Log in</button>
            <div>
                <p>Don't have an account ? </p>
                <a href="{{url_for('auth.register')}}">Sign Up &rarr;</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}